### ISSUE TITLE
Clicking suggestions takes us to the front page of Reformation rather than the product page

### ISSUE THREAD

**Issue by Matias-A** [treyholt/Suzie#24]
When showing a product suggestion, clicking the product should take the user to the relevant product page (maybe in a new tab)

**Comment by treyholt** [comment]
**Note**
We currently do not track the link to the product, so we will need to incorporate this into our firebase data.

**Comment by Matias-A** [comment]
Opened issue #28 to help us tackle this one

**Comment by Matias-A** [comment]
Issue fixed in most recent update
