### ISSUE TITLE
Extension crashes with Uncaught TypeError

### ISSUE THREAD

**Issue by Matias-A** [treyholt/Suzie#34]
![image](https://user-images.githubusercontent.com/8319613/117524094-9fb4cb80-af81-11eb-8482-23585fdb6c70.png)

**Comment by Matias-A** [comment]
Update: Doesn't crash completely. But, sometimes seems like the popup doesn't show up when it should. Maybe caused by some sort of a delay in how Zara loads?

**Comment by treyholt** [comment]
Fixed in latest PR
