### ISSUE TITLE
Goals for Next Week (April 21)

### ISSUE THREAD

**Issue by kate-rydberg** [treyholt/Suzie#6]
Great to see you all today! As I mentioned in our SGM, each week I'll post an issue with the goals we discuss for next week. The goals will generally be a mix of what I would like to see and things you all would like to get done in the next week. We'll start the next SGM going over how you all are doing on these goals. Feel free to comment on this issue if you have questions or concerns, or you can always shoot me an email (rydbergk@)!

_Note: haven't yet heard back about this repo vs. the CS194 repo. I'm posting this issue here for now since this is your current repo, but I'll let you know when I have an update._

Goals for next week:

- Start list of core features vs. stretch goal features
- Set up tech stack 
- Continue to work on documentation
- Experiment with uploading a lot of data into firebase 
- Early user testing
- Start working on documentation - all of the above bullet points would be great candidates for documentation :)
- Fill out [Work Tracking doc](https://docs.google.com/spreadsheets/d/1srqtbhv7nGIdjTRMVPvHh1II5cYNMlZaarponMpE_eo/edit?usp=sharing) with summary of what you've been working on for weeks 1-4 (totally fine if first few weeks are sparse)

**Comment by treyholt** [comment]
> Great to see you all today! As I mentioned in our SGM, each week I'll post an issue with the goals we discuss for next week. The goals will generally be a mix of what I would like to see and things you all would like to get done in the next week. We'll start the next SGM going over how you all are doing on these goals. Feel free to comment on this issue if you have questions or concerns, or you can always shoot me an email (rydbergk@)!
> 
> _Note: haven't yet heard back about this repo vs. the CS194 repo. I'm posting this issue here for now since this is your current repo, but I'll let you know when I have an update._
> 
> Goals for next week:
> 
> * Start list of core features vs. stretch goal features
> * Set up tech stack
> * Continue to work on documentation
> * Experiment with uploading a lot of data into firebase
> * Early user testing
> * Start working on documentation - all of the above bullet points would be great candidates for documentation :)
> * Fill out [Work Tracking doc](https://docs.google.com/spreadsheets/d/1GhzuSmBChQv6hE9DJMMW7-aoMHsIMc8DPxRsxoY5NCM/edit?usp=sharing) with summary of what you've been working on for weeks 1-4 (totally fine if first few weeks are sparse)

I think you may have linked the a different team's work tracking doc @kate-rydberg

**Comment by kate-rydberg** [comment]
Oops, sorry about that - I updated the above link!

**Comment by treyholt** [comment]
Possible question for next SGM: 
What's the best practice for sharing sensitive files that need to live locally that we would all need to authenticate to run certain bits of code?
